version: "3"
services:

  db:
    restart: always
    image: postgres:11.0
    expose:
      - 5432


  web:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:8000
    depends_on:
      - db
    command: python /app/manage.py runserver 127.0.0.1:8000
